EDI_App/EDI_App/Controllers/MappingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EDI_App.Helper;
using EDI_App.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EDI_App.Controllers
{
    public class MappingController : Controller
    {
        [HttpGet]
        public IActionResult List()
        {
            List<Mapping_M> lst_Mapping = new List<Mapping_M>();
            Mapping_Helper mapping_Helper = new Mapping_Helper();
            lst_Mapping = mapping_Helper.GetAll_VendorMappingFields();
            return View(lst_Mapping);
        }

        [HttpGet]
        public IActionResult Create()
        {
            try
            {
                List<SelectListItem> vendorListSelectListItem = new List<SelectListItem>();

                Mapping_Helper mapping_Helper = new Mapping_Helper();
                var vendor_Ddl = mapping_Helper.GetAll_Vendors();
                if (vendor_Ddl != null)
                {
                    vendorListSelectListItem = (from p in vendor_Ddl.AsEnumerable()
                                                orderby p.Vendor_Name ascending
                                                select new SelectListItem
                                                {
                                                    Text = p.Vendor_Name.ToString(),
                                                    Value = p.Vendor_Id.ToString()//,
                                                }).ToList();

                }

                ViewBag.Vendors = vendorListSelectListItem;
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }
            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind(include: "Vendor_Id,Invoice_Id_Alias,Invoice_Date_Alias,Invoice_Amount_Alias,Customer_Id_Alias,Customer_Name_Alias,Product_Id_Alias,Product_Name_Alias,Product_Quantity_Alias,Product_Unit_Alias,Product_Price_Alias,Product_Description_Alias,Product_Discount_Alias,Product_Amount_Alias,Invoice_Amount_Alias")]Mapping_M mapping)
        {
            Operation_Message msg = new Operation_Message();
            Mapping_Helper mapping_Helper = new Mapping_Helper();

            try
            {
                if (ModelState.IsValid)
                {
                    mapping.Mode = 'I';
                    msg = mapping_Helper.Mapping_InsertUpdate(mapping);
                }

                //Bind Vendor List
                {
                    List<SelectListItem> vendorListSelectListItem = new List<SelectListItem>();
                    mapping_Helper = new Mapping_Helper();

                    var vendor_Ddl = mapping_Helper.GetAll_Vendors();
                    if (vendor_Ddl != null)
                    {
                        vendorListSelectListItem = (from p in vendor_Ddl.AsEnumerable()
                                                    orderby p.Vendor_Name ascending
                                                    select new SelectListItem
                                                    {
                                                        Text = p.Vendor_Name.ToString(),
                                                        Value = p.Vendor_Id.ToString(),
                                                        Selected = false
                                                    }).ToList();

                    }
                    ViewBag.Vendors = vendorListSelectListItem;
                }

                if (msg.Is_success)
                {
                    ViewBag.Message_Id = msg.Return_Message_Id;
                    ViewBag.Message = msg.Return_Message;

                    List<Mapping_M> lst_mapping = new List<Mapping_M>();
                    mapping_Helper = new Mapping_Helper();
                    lst_mapping = mapping_Helper.GetAll_VendorMappingFields();
                    return View("List", lst_mapping);
                    //if (msg.Return_Message_Id == (int)Messages_Ids.Insert)
                    //{
                    //    ViewBag.Message_Id = msg.Return_Message_Id;
                    //    ViewBag.Message = msg.Return_Message;
                    //    return View("List", lst_mapping);
                    //}

                    //else
                    //{
                    //    ViewBag.Message_Id = msg.Return_Message_Id;
                    //    ViewBag.Message = msg.Return_Message;
                    //    return View("Create", mapping);
                    //}
                }
                else
                {
                    ViewBag.Message_Id = msg.Return_Message_Id;
                    ViewBag.Message = msg.Return_Message;
                    return View("Create", mapping);
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View("Create", mapping);
            }
        }

        [HttpGet]
        public IActionResult Edit(long vendor_Id)
        {
            List<SelectListItem> vendorListSelectListItem = new List<SelectListItem>();
            Mapping_M mapping = new Mapping_M();
            Mapping_Helper mapping_Helper = new Mapping_Helper();
            try
            {
                var vendor_Ddl = mapping_Helper.GetAll_Vendors();
                if (vendor_Ddl != null)
                {
                    vendorListSelectListItem = (from p in vendor_Ddl.AsEnumerable()
                                                orderby p.Vendor_Name ascending
                                                select new SelectListItem
                                                {
                                                    Text = p.Vendor_Name.ToString(),
                                                    Value = p.Vendor_Id.ToString(),
                                                    Selected = (long)p.Vendor_Id == vendor_Id ? true : false
                                                }).ToList();

                }
                mapping_Helper = new Mapping_Helper();
                mapping = mapping_Helper.Get_VendorMappingFields(vendor_Id);
                ViewBag.Vendors = vendorListSelectListItem;
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }
            return View(mapping);
        }

        [HttpPost]
        public ActionResult Edit([Bind(include: "Vendor_Id,Invoice_Id_Alias,Invoice_Date_Alias,Invoice_Amount_Alias,Customer_Id_Alias,Mapping_Id,Customer_Name_Alias,Product_Id_Alias,Product_Name_Alias,Product_Quantity_Alias,Product_Unit_Alias,Product_Price_Alias,Product_Description_Alias,Product_Discount_Alias,Product_Amount_Alias,Invoice_Amount_Alias")]Mapping_M mapping)
        {
            Operation_Message msg = new Operation_Message();
            Mapping_Helper mapping_Helper = new Mapping_Helper();

            try
            {
                if (ModelState.IsValid)
                {
                    mapping.Mode = 'U';
                    msg = mapping_Helper.Mapping_InsertUpdate(mapping);
                }

                //Bind Vendor List
                {
                    List<SelectListItem> vendorListSelectListItem = new List<SelectListItem>();

                    mapping_Helper = new Mapping_Helper();
                    var vendor_Ddl = mapping_Helper.GetAll_Vendors();
                    if (vendor_Ddl != null)
                    {
                        vendorListSelectListItem = (from p in vendor_Ddl.AsEnumerable()
                                                    orderby p.Vendor_Name ascending
                                                    select new SelectListItem
                                                    {
                                                        Text = p.Vendor_Name.ToString(),
                                                        Value = p.Vendor_Id.ToString(),
                                                        Selected = false
                                                    }).ToList();

                    }
                    ViewBag.Vendors = vendorListSelectListItem;
                }

                if (msg.Is_success)
                {
                    List<Mapping_M> lst_mapping = new List<Mapping_M>();
                    mapping_Helper = new Mapping_Helper();
                    lst_mapping = mapping_Helper.GetAll_VendorMappingFields();

                    ViewBag.Message_Id = msg.Return_Message_Id;
                    ViewBag.Message = msg.Return_Message;
                    return View("List", lst_mapping);
                    //if (msg.Return_Message_Id == (int)Messages_Ids.Update)
                    //{
                    //    return View("List", lst_mapping);
                    //}

                    //else
                    //{
                    //    return View("Create", mapping);
                    //}
                }
                else
                {
                    ViewBag.Message_Id = msg.Return_Message_Id;
                    ViewBag.Message = msg.Return_Message;
                    return View();
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
        }


        [HttpGet]
        public JsonResult Get_VendorMappingFields(long vendor_Id)
        {
            Mapping_M mapping = new Mapping_M();
            Mapping_Helper mapping_Helper = new Mapping_Helper();

            try
            {
                if (vendor_Id != 0)
                {
                    mapping = mapping_Helper.Get_VendorMappingFields(vendor_Id);
                }

            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }
            return (Json(mapping));

EDI_App/EDI_App/Views/Mapping/List.cshtml
@model IEnumerable<EDI_App.Models.Mapping_M>
    ViewData["Title"] = "List";
}
<script src="~/Pages/Common_Ids.js"></script>
<script src="~/Pages/js/Mapping/Mapping_List.js"></script>
<main>
    <div class="container-fluid" style=" margin-left: 213px;width: 88%;">
        <div class="col-lg-12" style="margin-top:32px">
            <div class="card shadow-lg border-0 rounded-lg mt-12">
                <div class="col-sm-12 card-header">
                    <div class="col-sm-10" style="float:left">
                        <h3 class="text-center font-weight-light my-6">Vendor Fields Mapping</h3>
                    </div>
                    <div class="col-sm-2" style="float:right">
                        <button class="btn btn-primary btn-sm float-right " onclick="location.href='@Url.Action("Create", "Mapping")'" id="btn_FieldMapping"><i class="fa fa-plus" aria-hidden="true"></i> New</button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="col-sm-12">
                        <table class="table table-hover table-sm functional-team-view" id="tbl_MappingList">
                            <thead>
                                <tr>
                                    <th>Vendor Name</th>
                                    <th>Customer Id</th>
                                    <th>Invoice Id</th>
                                    <th>Invoice Date</th>
                                    <th>Product ID</th>
                                    <th>Product Name</th>
                                    <th class="text-center"></th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var item in Model)
                                {
                                    <tr class="listrow">
                                        <td style="text-align: justify;" id="lnk_testCaseName">
                                            @Html.HiddenFor(modelItem => item.Mapping_Id)
                                            <a href="javascript:void(0)" title="Edit." id="@item.Vendor_Id" onclick="location.href='@Url.Action("Edit", "Mapping")?vendor_Id='+@item.Vendor_Id">
                                                @Html.DisplayFor(modelItem => item.Vendor_Name)
                                            </a>
                                        </td>
                                        <td style="text-align: justify;">
                                            @Html.DisplayFor(modelItem => item.Customer_Id_Alias)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Invoice_Id_Alias)
                                        </td>
                                        <td style="text-align: justify;">
                                            @Html.DisplayFor(modelItem => item.Invoice_Date_Alias)
                                        </td>
                                        <td style="text-align: justify;">
                                            @Html.DisplayFor(modelItem => item.Product_Id_Alias)
                                        </td>
                                        <td style="text-align: justify;">
                                            @Html.DisplayFor(modelItem => item.Product_Name_Alias)
                                        </td>
                                        <td class="action-icon">
                                            <div class="text-center" style="width: 78px;">
                                                <a href="javascript:void(0)" id="@item.Mapping_Id" class="edit_Mapping_Id">
                                                    <i class="fas fa-edit" onclick="location.href='@Url.Action("Edit", "Mapping")?vendor_Id='+@item.Vendor_Id"></i>
                                                </a>
                                                <a href="javascript:void(0)" id="@item.Vendor_Id" class="Vendor_Id">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>

                                    </tr>
                                }
                            </tbody>
                        </table>
                        <div class="card-body" id="div_pagination">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="dataTables_info" id="div_paginationInfo" role="status" aria-live="polite"></div>
                                </div>
                                <div class="col-sm-6 ">
                                    <nav aria-label="pagination" class="float-right">
                                        <ul class="pagination pagination-flat pagination-rounded" id="lst_pagination"></ul>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @if (ViewBag.Message != null)
        {
            <script>
                    $(document).ready(function () {
                        var msg_Id = "@ViewBag.Message_Id";
                        var msg = "@ViewBag.Message";
                        if (msg_Id != null && msg_Id != undefined) {
                            if (msg_Id == Message_Ids.Insert || msg_Id == Message_Ids.Update || msg_Id == Message_Ids.Delete) {
                                 alert(msg);
                            }
                            else if (msg_Id == Message_Ids.Error) {
                                alert(msg);
                            }
                            else {
                                 alert(msg);
                            }
                        }
                });

            </script>
        }
    </div>
</main>