EDI_App/EDI_App/Controllers/VendorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EDI_App.Helper;
using EDI_App.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EDI_App.Controllers
{
    public class VendorController : Controller
    {
               
        [HttpGet]
        public IActionResult List()
        {
            List<Vendor_M> lst_mapping = new List<Vendor_M>();
            Vendor_Helper mapping_Helper = new Vendor_Helper();
            lst_mapping = mapping_Helper.Get_Vendors();
            return View(lst_mapping);
        }


        [HttpGet]
        public IActionResult Create()
        {
            try
            {
                List<SelectListItem> State_ListSelectListItem = new List<SelectListItem>();

                Customer_M customer = new Customer_M();
                Customer_Helper customer_Helper = new Customer_Helper();
                var state_Ddl = customer_Helper.GetAll_States();
                if (state_Ddl != null)
                {
                    State_ListSelectListItem = (from p in state_Ddl.AsEnumerable()
                                                orderby p.State ascending
                                                select new SelectListItem
                                                {
                                                    Text = p.State.ToString(),
                                                    Value = p.State_Id.ToString(),
                                                    Selected = p.State.ToUpper().Trim() == "TEXAS" ? true : false
                                                }).ToList();

                }
                ViewBag.States = State_ListSelectListItem;



                List<SelectListItem> Zip_ListSelectListItem = new List<SelectListItem>();
                Vendor_M vendor = new Vendor_M();
                Vendor_Helper vendor_Helper = new Vendor_Helper();
                var zips_Ddl = vendor_Helper.GetAll_Zip(vendor.State_Id, "");
                if (zips_Ddl != null)
                {
                    Zip_ListSelectListItem = (from p in zips_Ddl.AsEnumerable()
                                              orderby p.Zip_Code ascending
                                              select new SelectListItem
                                              {
                                                  Text = p.Zip_Code.ToString(),
                                                  Value = p.Zip_Code_Id.ToString()//,
                                              }).ToList();

                }
                ViewBag.Zip_Code = Zip_ListSelectListItem;


            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }
            return View();
        }


        // Insert_Vender
        [HttpPost]
        public ActionResult Create([Bind(include: "Vendor_Name,Address,City,Country,Zip_Code,Phone_Number,Email_Address,Secondary_Email_Address ,Fax_Number ,Tax_Number, Contact_Person ,State,State_Id ,Website, Vendor_Code")]Vendor_M vendor1)
        {
            Operation_Message msg = new Operation_Message();
            Vendor_Helper vendor_Helper = new Vendor_Helper();

            try
            {
                if (ModelState.IsValid)
                {
                    vendor1.Mode = 'I';
                    msg = vendor_Helper.Vendor_Insert(vendor1);
                }


                List<SelectListItem> State_ListSelectListItem = new List<SelectListItem>();

                Customer_M customer = new Customer_M();
                Customer_Helper customer_Helper = new Customer_Helper();
                var state_Ddl = customer_Helper.GetAll_States();
                if (state_Ddl != null)
                {
                    State_ListSelectListItem = (from p in state_Ddl.AsEnumerable()
                                                orderby p.State ascending
                                                select new SelectListItem
                                                {
                                                    Text = p.State.ToString(),
                                                    Value = p.State_Id.ToString(),
                                                    Selected = (long)p.State_Id == customer.State_Id ? true : false
                                                }).ToList();

                }
                ViewBag.States = State_ListSelectListItem;



                if (msg.Is_success)
                {
                    ViewBag.Message_Id = msg.Return_Message_Id;
                    ViewBag.Message = msg.Return_Message;

                    List<Vendor_M> lst_mapping = new List<Vendor_M>();
                    vendor_Helper = new Vendor_Helper();
                    lst_mapping = vendor_Helper.Get_Vendors();

                    return View("List", lst_mapping);
                }
                else
                {
                    ViewBag.Message_Id = msg.Return_Message_Id;
                    ViewBag.Message = msg.Return_Message;
                    List<Vendor_M> lst_mapping = new List<Vendor_M>();
                    vendor_Helper = new Vendor_Helper();
                    lst_mapping = vendor_Helper.Get_Vendors();

                    return View("List", lst_mapping);
                    // return View();



                }
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
        }

        //delete vendor

        [HttpGet]
        public JsonResult Delete(long vendor_Id)//, bool user_Confirmation_To_Delete_Test_Script)
        {
            Operation_Message operation_Message = new Operation_Message();
            try
            {
                Vendor_Helper _testCase_Helper = new Vendor_Helper();
                if (vendor_Id > 0)
                {
                    operation_Message = _testCase_Helper.Delete_Vendor(vendor_Id);
                    if (operation_Message.Is_success)
                    {
                        if (operation_Message.Return_Message_Id == (int)Messages_Ids.Delete)
                        {
                            ViewBag.Message_Id = (int)Messages_Ids.Delete;
                            operation_Message.Return_Message_Id = (int)Messages_Ids.Delete;

                            ViewBag.Message = operation_Message.Return_Message;
                            operation_Message.Return_Message = operation_Message.Return_Message;
                        }
                        else if (operation_Message.Return_Message_Id == (int)Messages_Ids.Other)
                        {
                            ViewBag.Message_Id = (int)Messages_Ids.Other;
                            operation_Message.Return_Message_Id = (int)Messages_Ids.Other;

                            ViewBag.Message = operation_Message.Return_Message;
                            operation_Message.Return_Message = operation_Message.Return_Message;
                        }
                        else
                        {
                            ViewBag.Message_Id = (int)Messages_Ids.Error;
                            operation_Message.Return_Message_Id = (int)Messages_Ids.Error;

                            ViewBag.Message = operation_Message.Return_Message;
                            operation_Message.Return_Message = operation_Message.Return_Message;
                        }
                    }
                    else
                    {
                        ViewBag.Message_Id = (int)Messages_Ids.Error;
                        ViewBag.Message = "Error";
                    }
                }
                else
                {
                    ViewBag.Message_Id = (int)Messages_Ids.Error;
                    ViewBag.Message = "Error";
                }
            }
            catch (Exception _ex)
            {
                ViewBag.Message_Id = (int)Messages_Ids.Error;
                ViewBag.Message = "Error";
            }
            return Json(operation_Message);
        }

        //update Vendor

        [HttpGet]
        public IActionResult Edit(long vendor_Id)
        {

            List<Vendor_M> lst_vendor = new List<Vendor_M>();
            Vendor_M vendor = new Vendor_M();

            try
            {

                Vendor_Helper vendor_Helper = new Vendor_Helper();
                vendor = vendor_Helper.Get_VendorDetails(vendor_Id);
                List<SelectListItem> State_ListSelectListItem = new List<SelectListItem>();

                Customer_M customer = new Customer_M();
                Customer_Helper customer_Helper = new Customer_Helper();
                var state_Ddl = customer_Helper.GetAll_States();
                if (state_Ddl != null)
                {
                    State_ListSelectListItem = (from p in state_Ddl.AsEnumerable()
                                                orderby p.State ascending
                                                select new SelectListItem
                                                {
                                                    Text = p.State.ToString(),
                                                    Value = p.State_Id.ToString(),
                                                    Selected = (long)p.State_Id == customer.State_Id ? true : false
                                                }).ToList();

                }
                ViewBag.States = State_ListSelectListItem;
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }


            return View(vendor);
        }

        [HttpPost]

EDI_App/EDI_App/Views/Vendor/List.cshtml
@model IEnumerable<EDI_App.Models.Vendor_M>
    ViewData["Title"] = "List";
}
<script src="~/Pages/Common_Ids.js"></script>
<script src="~/Pages/js/Vendor/Vendor_List.js"></script>
<main>
    <div class="container-fluid" style=" margin-left: 213px;width: 88%;">
        <div class="col-lg-12" style="margin-top:32px">
            <div class="card shadow-lg border-0 rounded-lg mt-12">
                <div class="col-sm-12 card-header">
                    <div class="col-sm-10" style="float:left">
                        <h3 class="text-center font-weight-light my-6">Vendor </h3>
                    </div>
                    <div class="col-sm-2" style="float:right">
                        <button class="btn btn-primary btn-sm float-right " onclick="location.href='@Url.Action("Create", "Vendor")'" id="btn_FieldVendor"><i class="fa fa-plus" aria-hidden="true"></i> New</button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="col-sm-12">
                        <table class="table table-hover table-sm functional-team-view" id="tbl_VendorList">
                            <thead>
                                <tr>
                                    @*<th>Vendor Name</th>
                                        <th>Vendor Address</th>
                                        <th>Vendor Country</th>
                                        <th>Vendor Zip</th>
                                        <th>Vendor State</th>
                                        <th>Vendor Code</th>*@

                                    <th>Name</th>
                                    <th>Code</th>
                                    <th>State</th>
                                    <th>Country</th>
                                    <th>Zip</th>
                                    <th>Tax Number</th>
                                    <th>Fax Number</th>

                                    <th class="text-center"></th>
                                </tr>
                            </thead>
                            <tbody>


                                @foreach (var item in Model)
                                {
                                    <tr class="listrow">


                                        <td style="text-align: justify;" id="lnk_testCaseName">
                                            @Html.HiddenFor(modelItem => item.Vendor_Name)
                                            <a href="javascript:void(0)" title="Edit" id="@item.Vendor_Id" onclick="location.href='@Url.Action("Edit", "Vendor")?vendor_Id='+@item.Vendor_Id">
                                                @Html.DisplayFor(modelItem => item.Vendor_Name)
                                            </a>
                                        </td>


                                        <td style="text-align: justify;">
                                            @Html.DisplayFor(modelItem => item.Vendor_Code)
                                        </td>


                                        <td>
                                            @Html.DisplayFor(modelItem => item.State)
                                        </td>


                                        <td style="text-align: justify;">
                                            @Html.DisplayFor(modelItem => item.Country)
                                        </td>


                                        <td style="text-align: justify;">
                                            @Html.DisplayFor(modelItem => item.Zip_Code)
                                        </td>

                                        <td style="text-align: justify;">
                                            @Html.DisplayFor(modelItem => item.Tax_Number)
                                        </td>


                                        <td style="text-align: justify;">
                                            @Html.DisplayFor(modelItem => item.Fax_Number)
                                        </td>




                                        <td class="action-icon">
                                            <div class="text-center" style="width: 78px;">
                                                <a href="javascript:void(0)" id="@item.Vendor_Id" class="edit_Vendor_Id">
                                                    @* <i class="fas fa-edit" onclick="location.href='@Url.Action("Edit", "Vendor")?vendor_Id='+@item.Vendor_Id"></i>*@
                                                    <i class="fas fa-edit" onclick="location.href='@Url.Action("Edit", "Vendor")?vendor_Id='+@item.Vendor_Id"></i>
                                                </a>
                                                <a href="javascript:void(0)" id="@item.Vendor_Id" class="Vendor_Id">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>

                                    </tr>
                                }
                            </tbody>
                        </table>
                        <div class="card-body" id="div_pagination">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="dataTables_info" id="div_paginationInfo" role="status" aria-live="polite"></div>
                                </div>
                                <div class="col-sm-6 ">
                                    <nav aria-label="pagination" class="float-right">
                                        <ul class="pagination pagination-flat pagination-rounded" id="lst_pagination"></ul>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                @*<div class="card-footer text-center">
                        <div class="small"><a href="register.html">Need an account? Sign up!</a></div>
                    </div>*@
            </div>
        </div>
        @if (ViewBag.Message != null)
        {
            <script>
                    $(document).ready(function () {
                        var msg_Id = "@ViewBag.Message_Id";
                        var msg = "@ViewBag.Message";
                        if (msg_Id != null && msg_Id != undefined) {
                            if (msg_Id == Message_Ids.Insert || msg_Id == Message_Ids.Update || msg_Id == Message_Ids.Delete) {
                              //  ssi_modal.notify('success', { position: 'right top', content: msg });
                                 alert(msg);
                            }
                            else if (msg_Id == Message_Ids.Error) {
                                alert(msg);
                                //ssi_modal.notify('error', { position: 'right top', content: msg });
                            }
                            else {
                               // ssi_modal.notify('info', { position: 'right top', content: msg });
                                 alert(msg);
                            }
                        }
                });

            </script>
        }
    </div>
</main>