EDI_App/EDI_App/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EDI_App.Helper;
using EDI_App.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EDI_App.Controllers
{
    public class CustomerController : Controller
    {
        [HttpGet]
        public IActionResult List()
        {
            List<Customer_M> lst_Customers = new List<Customer_M>();
            Customer_Helper customer_Helper = new Customer_Helper();
            lst_Customers = customer_Helper.GetAll_Customers();
            return View(lst_Customers);
        }

        [HttpGet]
        public IActionResult Create()
        {
            try
            {
                List<SelectListItem> Customer_TypeListSelectListItem = new List<SelectListItem>();
                List<SelectListItem> State_ListSelectListItem = new List<SelectListItem>();

                Customer_Helper customer_Helper = new Customer_Helper();

                var customer_Ddl = customer_Helper.GetAll_Customer_Types();
                if (customer_Ddl != null)
                {
                    Customer_TypeListSelectListItem = (from p in customer_Ddl.AsEnumerable()
                                                       orderby p.Customer_Type_Name ascending
                                                       select new SelectListItem
                                                       {
                                                           Text = p.Customer_Type_Name.ToString(),
                                                           Value = p.Customer_Type_Id.ToString()//,
                                                       }).ToList();

                }
                customer_Helper = new Customer_Helper();
                var state_Ddl = customer_Helper.GetAll_States();
                if (state_Ddl != null)
                {
                    State_ListSelectListItem = (from p in state_Ddl.AsEnumerable()
                                                       orderby p.State ascending
                                                       select new SelectListItem
                                                       {
                                                           Text = p.State.ToString(),
                                                           Value = p.State_Id.ToString()//,
                                                       }).ToList();

                } 
                ViewBag.Customers_Type = Customer_TypeListSelectListItem;
                ViewBag.States = State_ListSelectListItem;
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }
            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind(include: "Customer_Name,Customer_Code,Address,City,State,State_Id,Country,Email_Address,Secondary_Email_Address,Phone_Number,Fax_Number,Tax_Number,Zip,Status,Customer_Type_Id")]Customer_M customer)
        {
            Operation_Message msg = new Operation_Message();
            Customer_Helper customer_Helper = new Customer_Helper();

            try
            {
                if (ModelState.IsValid)
                {
                    customer.Mode = 'I';
                    msg = customer_Helper.InsertUpdate_Customer(customer);
                }

                //Bind Customer Type List
                {
                    List<SelectListItem> Customer_TypeListSelectListItem = new List<SelectListItem>();
                    List<SelectListItem> State_ListSelectListItem = new List<SelectListItem>();

                    customer_Helper = new Customer_Helper();

                    var customer_Ddl = customer_Helper.GetAll_Customers();
                    if (customer_Ddl != null)
                    {
                        Customer_TypeListSelectListItem = (from p in customer_Ddl.AsEnumerable()
                                                           orderby p.Customer_Name ascending
                                                           select new SelectListItem
                                                           {
                                                               Text = p.Customer_Name.ToString(),
                                                               Value = p.Customer_Type_Id.ToString(),
                                                               Selected = false
                                                           }).ToList();

                    }
                    customer_Helper = new Customer_Helper();
                    var state_Ddl = customer_Helper.GetAll_States();
                    if (state_Ddl != null)
                    {
                        State_ListSelectListItem = (from p in state_Ddl.AsEnumerable()
                                                    orderby p.State ascending
                                                    select new SelectListItem
                                                    {
                                                        Text = p.State.ToString(),
                                                        Value = p.State_Id.ToString()//,
                                                    }).ToList();

                    }

                    ViewBag.Customers_Type = Customer_TypeListSelectListItem;
                    ViewBag.States = State_ListSelectListItem;
                }

                if (msg.Is_success)
                {
                    ViewBag.Message_Id = msg.Return_Message_Id;
                    ViewBag.Message = msg.Return_Message;

                    List<Customer_M> lst_Customers = new List<Customer_M>();
                    customer_Helper = new Customer_Helper();
                    lst_Customers = customer_Helper.GetAll_Customers();

                    return View("List", lst_Customers);
                }
                else
                {
                    ViewBag.Message_Id = msg.Return_Message_Id;
                    ViewBag.Message = msg.Return_Message;
                    return View();
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
        }

        [HttpGet]
        public IActionResult Edit(long customer_Id)
        {
            List<SelectListItem> Customer_TypeListSelectListItem = new List<SelectListItem>();
            List<SelectListItem> State_ListSelectListItem = new List<SelectListItem>();

            Customer_M customer = new Customer_M();
            Customer_Type customer_Type = new Customer_Type();
            Customer_Helper customer_Helper = new Customer_Helper();
            try
            {
                customer = customer_Helper.Get_Customer(customer_Id);
                customer_Helper = new Customer_Helper();

                var customer_Type_Ddl = customer_Helper.GetAll_Customer_Types();
                if (customer_Type_Ddl != null)
                {
                    Customer_TypeListSelectListItem = (from p in customer_Type_Ddl.AsEnumerable()
                                                       orderby p.Customer_Type_Name ascending
                                                       select new SelectListItem
                                                       {
                                                           Text = p.Customer_Type_Name.ToString(),
                                                           Value = p.Customer_Type_Id.ToString(),
                                                           Selected = (long)p.Customer_Type_Id == customer.Customer_Type_Id ? true : false
                                                       }).ToList();

                }
                customer_Helper = new Customer_Helper();
                var state_Ddl = customer_Helper.GetAll_States();
                if (state_Ddl != null)
                {
                    State_ListSelectListItem = (from p in state_Ddl.AsEnumerable()
                                                orderby p.State ascending
                                                select new SelectListItem
                                                {
                                                    Text = p.State.ToString(),
                                                    Value = p.State_Id.ToString(),
                                                    Selected = (long)p.State_Id == customer.State_Id ? true : false
                                                }).ToList();

                }

                ViewBag.Customers_Type = Customer_TypeListSelectListItem;
                ViewBag.States = State_ListSelectListItem;
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }
            return View(customer);
        }

        [HttpPost]
        public ActionResult Edit([Bind(include: "Customer_Id,Customer_Name,Customer_Code,Address,City,State,,State_Id,Country,Email_Address,Secondary_Email_Address,Phone_Number,Fax_Number,Tax_Number,Zip,Status,Customer_Type_Id")]Customer_M customer)
        {
            Operation_Message msg = new Operation_Message();
            Customer_Helper customer_Helper = new Customer_Helper();

            try
            {
                if (ModelState.IsValid)
                {
                    customer.Mode = 'U';
                    msg = customer_Helper.InsertUpdate_Customer(customer);
                }

                //Bind Dropdown Lists
                {
                    List<SelectListItem> Customer_TypeListSelectListItem = new List<SelectListItem>();
                    List<SelectListItem> State_ListSelectListItem = new List<SelectListItem>();


                    customer_Helper = new Customer_Helper();
                    var customer_Ddl = customer_Helper.GetAll_Customers();

EDI_App/EDI_App/Views/Customer/List.cshtml
@model IEnumerable<EDI_App.Models.Customer_M>;
@{
    ViewData["Title"] = "List";
}

<script src="~/Pages/Common_Ids.js"></script>
<script src="~/Pages/js/Customer/Customer_List.js"></script>
<main>
    <div class="container-fluid" style=" margin-left: 213px;width: 88%;">
        <div class="col-lg-12" style="margin-top:53px">
            <div class="card shadow-lg border-0 rounded-lg mt-12">
                <div class="col-sm-12 card-header">
                    <div class="col-sm-10" style="float:left">
                        <h3 class="text-center font-weight-light my-6">Customer List</h3>
                    </div>
                    <div class="col-sm-2" style="float:right">
                        <button class="btn btn-primary btn-sm float-right " onclick="location.href='@Url.Action("Create", "Customer")'" id="btn_Customer"><i class="fa fa-plus" aria-hidden="true"></i> New</button>
                    </div>
                </div>
                <div class="card-body">
                    <div class="col-sm-12">
                        <table class="table table-hover table-sm functional-team-view" id="tbl_CustomerList">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Account Type</th>
                                    <th>Customer Id/Code</th>
                                    <th>Address</th>
                                    <th>Email Address</th>
                                    <th>Status</th>
                                    <th class="text-center"></th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var item in Model)
                                {
                                    <tr class="listrow">
                                        <td style="text-align: justify;" id="lnk_testCaseName">
                                            @Html.HiddenFor(modelItem => item.Customer_Id)
                                            <a href="javascript:void(0)" title="Edit." id="@item.Customer_Id" onclick="location.href='@Url.Action("Edit", "Customer")?vendor_Id='+@item.Customer_Id">
                                                @Html.DisplayFor(modelItem => item.Customer_Name)
                                            </a>
                                        </td>
                                        <td style="text-align: justify;">
                                            @Html.DisplayFor(modelItem => item.Customer_Type_Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Customer_Code)
                                        </td>
                                        <td style="text-align: justify;">
                                            @Html.DisplayFor(modelItem => item.Address)
                                        </td>
                                        <td style="text-align: justify;">
                                            @Html.DisplayFor(modelItem => item.Email_Address)
                                        </td>

                                        @if (item.Status == false)
                                        {
                                            <td style="text-align: justify;">Active</td>
                                        }
                                        else
                                        {
                                            <td style="text-align: justify;">InActive</td>
                                        }

                                        <td class="action-icon">
                                            <div class="text-center" style="width: 78px;">
                                                <a href="javascript:void(0)" id="@item.Customer_Id" class="edit_Customer_Id">
                                                    <i class="fas fa-edit" onclick="location.href='@Url.Action("Edit", "Customer")?customer_Id='+@item.Customer_Id"></i>
                                                </a>
                                                <a href="javascript:void(0)" id="@item.Customer_Id" class="Customer_Id">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            </div>
                                        </td>

                                    </tr>
                                }
                            </tbody>
                        </table>
                        <div class="card-body" id="div_pagination">
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="dataTables_info" id="div_paginationInfo" role="status" aria-live="polite"></div>
                                </div>
                                <div class="col-sm-6 ">
                                    <nav aria-label="pagination" class="float-right">
                                        <ul class="pagination pagination-flat pagination-rounded" id="lst_pagination"></ul>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                @*<div class="card-footer text-center">
                        <div class="small"><a href="register.html">Need an account? Sign up!</a></div>
                    </div>*@
            </div>
        </div>
        @if (ViewBag.Message != null)
        {
            <script>
                    $(document).ready(function () {
                        var msg_Id = "@ViewBag.Message_Id";
                        var msg = "@ViewBag.Message";
                        if (msg_Id != null && msg_Id != undefined) {
                            if (msg_Id == Message_Ids.Insert || msg_Id == Message_Ids.Update || msg_Id == Message_Ids.Delete) {
                                 alert(msg);
                            }
                            else if (msg_Id == Message_Ids.Error) {
                                alert(msg);
                            }
                            else {
                                 alert(msg);
                            }
                        }
                });

            </script>
        }
    </div>
</main>